# Generated by Django 2.1.4 on 2019-01-12 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CityName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('county', models.CharField(blank=True, max_length=60)),
                ('state', models.CharField(blank=True, max_length=60)),
                ('country', models.CharField(default='United States', max_length=60)),
                ('area_key', models.CharField(blank=True, max_length=60)),
                ('area_name', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LatitudeLongitude',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.CharField(max_length=60)),
                ('longitude', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchCreteria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.TextField(blank=True)),
                ('laundry', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('search_titles_only', models.BooleanField(default=False)),
                ('has_image', models.BooleanField(default=True)),
                ('posted_today', models.BooleanField(default=False)),
                ('bundle_duplicates', models.BooleanField(default=True)),
                ('private_room', models.BooleanField(default=True)),
                ('private_bath', models.BooleanField(default=True)),
                ('cats_ok', models.BooleanField(default=True)),
                ('dogs_ok', models.BooleanField(default=True)),
                ('min_price', models.CharField(default=500, max_length=60)),
                ('max_price', models.CharField(default=1000, max_length=60)),
                ('min_ft', models.CharField(blank=True, max_length=60)),
                ('max_ft', models.CharField(blank=True, max_length=60)),
                ('min_bedrooms', models.IntegerField(default=1)),
                ('max_bedrooms', models.IntegerField(default=2)),
                ('min_bathrooms', models.IntegerField(default=1)),
                ('max_bathrooms', models.IntegerField(default=2)),
                ('no_smoking', models.BooleanField(default=True)),
                ('is_furnished', models.BooleanField(default=False)),
                ('wheelchair_access', models.BooleanField(default=False)),
                ('housing_type', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bedrooms', models.IntegerField(default=1)),
                ('url', models.URLField(blank=True)),
                ('image', models.CharField(blank=True, max_length=200)),
                ('laundry', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('has_image', models.BooleanField(default=False)),
                ('private_room', models.BooleanField(default=False)),
                ('private_bath', models.BooleanField(default=False)),
                ('cats_ok', models.BooleanField(default=False)),
                ('dogs_ok', models.BooleanField(default=False)),
                ('price', models.CharField(blank=True, max_length=60)),
                ('square_ft', models.CharField(blank=True, max_length=60)),
                ('no_of_bathrooms', models.IntegerField(default=1)),
                ('no_smoking', models.BooleanField(default=False)),
                ('is_furnished', models.BooleanField(default=False)),
                ('wheelchair_access', models.BooleanField(default=False)),
                ('housing_type', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubAreaName',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalCityName',
            fields=[
                ('cityname_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scrapper.CityName')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('scrapper.cityname',),
        ),
        migrations.CreateModel(
            name='PersonalLatitudeLongitude',
            fields=[
                ('latitudelongitude_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scrapper.LatitudeLongitude')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('scrapper.latitudelongitude',),
        ),
        migrations.CreateModel(
            name='PersonalSearchCreteria',
            fields=[
                ('searchcreteria_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scrapper.SearchCreteria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('scrapper.searchcreteria',),
        ),
        migrations.CreateModel(
            name='PersonalSearchResult',
            fields=[
                ('searchresult_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scrapper.SearchResult')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('scrapper.searchresult',),
        ),
        migrations.CreateModel(
            name='PersonalSubAreaName',
            fields=[
                ('subareaname_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scrapper.SubAreaName')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('scrapper.subareaname',),
        ),
        migrations.AddField(
            model_name='subareaname',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapper.CityName'),
        ),
        migrations.AddField(
            model_name='subareaname',
            name='latitude_longitude_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapper.LatitudeLongitude'),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='latitude_longitude_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapper.LatitudeLongitude'),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='search_creteria_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapper.SearchCreteria'),
        ),
        migrations.AddField(
            model_name='searchcreteria',
            name='latitude_longitude_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapper.LatitudeLongitude'),
        ),
        migrations.AddField(
            model_name='cityname',
            name='latitude_longitude_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrapper.LatitudeLongitude'),
        ),
    ]
