# Generated by Django 2.1.4 on 2019-01-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchresult',
            name='search_criteria',
        ),
        migrations.RemoveField(
            model_name='searchresult',
            name='short_description',
        ),
        migrations.AddField(
            model_name='searchresult',
            name='cats_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='dogs_ok',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='has_image',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='housing_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='is_furnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='laundry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='no_of_bathrooms',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='searchresult',
            name='no_smoking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='private_bath',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='private_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='query',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='square_ft',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='wheelchair_acccess',
            field=models.BooleanField(default=False),
        ),
    ]
