# Generated by Django 2.1.4 on 2019-01-04 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrapper', '0002_auto_20190104_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchCreteria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query', models.TextField()),
                ('laundry', models.BooleanField(default=False)),
                ('parking', models.BooleanField(default=False)),
                ('interest_point_coordinates', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=60)),
                ('longitude', models.CharField(max_length=60)),
                ('search_titles_only', models.BooleanField(default=False)),
                ('has_image', models.BooleanField(default=True)),
                ('posted_today', models.BooleanField(default=False)),
                ('bundle_duplicates', models.BooleanField(default=True)),
                ('private_room', models.BooleanField(default=True)),
                ('private_bath', models.BooleanField(default=True)),
                ('cats_ok', models.BooleanField(default=True)),
                ('dogs_ok', models.BooleanField(default=True)),
                ('min_price', models.CharField(blank=True, max_length=60)),
                ('max_price', models.CharField(blank=True, max_length=60)),
                ('min_ft2', models.CharField(blank=True, max_length=60)),
                ('max_ft2', models.CharField(blank=True, max_length=60)),
                ('min_bedrooms', models.IntegerField(blank=True)),
                ('max_bedrooms', models.IntegerField(blank=True)),
                ('min_bathrooms', models.IntegerField(blank=True)),
                ('max_bathrooms', models.IntegerField(blank=True)),
                ('no_smoking', models.BooleanField(default=True)),
                ('is_furnished', models.BooleanField(default=False)),
                ('wheelchair_acccess', models.BooleanField(default=False)),
                ('housing_type', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalSearchCreteria',
            fields=[
                ('searchcreteria_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='scrapper.SearchCreteria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('scrapper.searchcreteria',),
        ),
    ]
